[package]
name = "perlin_terrain"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
noise = "0.9.0"
rand = "0.9.1"
rand_distr = "0.5.1"

[profile.dev]
opt-level = 1

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3.2", features = ["wasm_js"]}
getrandom02 = { package = "getrandom", version = "0.2", features = ["js"] }
